### ISSUE TITLE
Custom html layouts

### ISSUE THREAD

**Issue by cbrew** [davidjurgens/potato#61]
It may be worth documenting the fact that  if you want to specify a custom html  layout, the path that you provide in the .yml config file has to be a full path. A path relative to the current directory does not work.  Might be worth a code change too, to allow relative paths.

**Comment by Jiaxin-Pei** [comment]
Hi @cbrew,

Thanks a lot for the heads up! We do support relative path for the custom HTML layout. For example, in the [politeness rating template](https://github.com/davidjurgens/potato/tree/master/project-hub/politeness_rating), the HTML layout is [templates/layout.html](https://github.com/davidjurgens/potato/blob/master/project-hub/politeness_rating/templates/layout.html). In the .yaml file, it uses `"html_layout": "templates/layout.html"` to point to this custom template.

Could you provide more details of the issue you saw?

Thanks!!

**Comment by Jiaxin-Pei** [comment]
I see! Thanks a lot for bringing this up and sorry for the confusion! We will revise the documentation and make it clearer!
