### ISSUE TITLE
user_config setting did not work 

### ISSUE THREAD

**Issue by WuXuanxin** [davidjurgens/potato#62]
Hello. I've set my configuration to allow only the user with the username "email address", as shown below:
```
    "user_config": {
      "allow_all_users": False,
      "users": 
        {
          "username": "email address",
          "password": "password"
        }
    },
```
Yet, I can still access the system with any created account. Can you guide me on how to fix this?

**Comment by Jiaxin-Pei** [comment]
@WuXuanxin This function was temporarily removed in previous updates as we could allow people to register directly through the login page. Could you elaborate more on your specific use case?

**Comment by WuXuanxin** [comment]
> @WuXuanxin This function was temporarily removed in previous updates as we could allow people to register directly through the login page. Could you elaborate more on your specific use case?

Thanks for your quick reply. Due to security concerns, I'm unable to set up a VPN at my workplace. I'd like to set up potato on a server with open ports. However, my current dataset, which requires annotation, cannot be publicly distributed. I want only my annotators to access the system, rather than allowing access to anyone who creates an account.

**Comment by Jiaxin-Pei** [comment]
@WuXuanxin I just made an [update](https://github.com/davidjurgens/potato/commit/8cf5c66094ecc08997a67e92a3b5d78ecb189c67) to support this feature, please upgrade potato-annotation or pull the latest version from GitHub. You could check the documentation [here](https://potato-annotation.readthedocs.io/en/latest/user_and_collaboration/#set-up-authorized-users).

**Comment by WuXuanxin** [comment]
@Jiaxin-Pei  Amazing! Thank you so much.

**Comment by Jiaxin-Pei** [comment]
issue fixed

**Comment by Jiaxin-Pei** [comment]
Issue fixed
