### ISSUE TITLE
"Start directly from the github repo" Failed on windows

### ISSUE THREAD

**Issue by XeonWangYue** [davidjurgens/potato#63]
I work by following steps on Windows:
1. git clone repo
2. pip install -r requirements.txt
3. python potato/flask_server.py start project-hub/simple_examples/configs/simple-check-box.yaml -p 8000

```shell
get error:
Traceback
  File potato\flask_server.py, line 2673 in <module>
    main()
  File potato\flask_server.py line 266 in main
     run_server(args)
  File potato\flask_server.py line 2586 in run_server
    init_config(args)
  File potato\server_utils\config_module.py line 22 in init_config
    if split_path[-2] == "configs":
IndexError: list index out of range
```

I add a print in `potato\server_utils\config_module.py` between line 21 and 22, get a DOS style path, like `"C:\\code\\potato\\..."`.
But `split_path` split it default by '/', witch is a Linux/Unix style path.

I simply solve the problem  by changing '/' to "\\" on line 21.

Maybe the project is just for linux now, would you like to fix that?

**Comment by Jiaxin-Pei** [comment]
Hi @XeonWangYue, thanks a lot for raising this issue! I will take a look and fix it!

**Comment by XeonWangYue** [comment]
Yes, it's working. I really appreciate it. 

Actually there's an advice. I saw bootstrap is import by CDN. Unfortunnately i have to use potato in an isolated network, which only allow git and some mirrors like pip and npm and CDN is not avaliable. Maybe a bootstrap-intergrated version can be created and will help a lot. And of course, the style is not important for me,

Thanks again, and i think the issue can be closed.
