### ISSUE TITLE
Previewing with Prolific before the study is published?

### ISSUE THREAD

**Issue by myracheng** [davidjurgens/potato#85]
Hi! I am trying to use your interface to set up a study on Prolific. However, I do not want to publish my study on Prolific yet, but I would like to be able to preview the interface locally before I publish it. However, when I try to put a dummy string in place of the Prolific token, and also populate the Prolific config dictionary with dummy data, and then run the app, I still get the error "Please login to annotate or you are using the wrong link". Is there any way to get around this?

Thanks!
Myra

**Comment by Jiaxin-Pei** [comment]
Hi @myracheng,

You can simply comment out the 'prolific_config' dict and switch the 'login_type' to 'password' or 'url_direct'.

If you switch to `password`, you can directly login with `localhost:port_id`
```
    #"prolific": {
    #    "config_file_path": 'configs/prolific_config.yaml'
    #},

    #defining the ways annotators entering the annotation system
    "login": {
       "type": 'password',    #can be 'password' or 'url_direct'
    },
```

If you switch to `url_direct`, then you can use login with `localhost:port_id` plus all the defined url_arguments, for example `localhost:8000/?PROLIFIC_PID=123&STUDY_ID=123&SESSION_ID=123`

```
    #"prolific": {
    #    "config_file_path": 'configs/prolific_config.yaml'
    #},

  "login": {
     "type": 'url_direct',    #can be 'password' or 'url_direct'
     "url_argument": ['PROLIFIC_PID','STUDY_ID','SESSION_ID'] # when the login type is set to 'url_direct', 'url_argument' must be setup for a direct url argument login

  },
```
Let me know if you need more help on this!
