### ISSUE TITLE
Space out radio choices in horizontal mode

### ISSUE THREAD

**Issue by jl3676** [davidjurgens/potato#93]
Hi, I was wondering if there's a way to space out the choices under the radio annotation scheme when they are aligned horizontally. The choices look too close to each other and I'd like to insert more whitespace between adjacent choices, but I'm not sure how to do that. I'd appreciate any help with this! 

![image](https://github.com/user-attachments/assets/19697763-dff2-4981-869e-fa7d9bd14530)

**Comment by Jiaxin-Pei** [comment]
Hi @jl3676,

I think there are two potential solutions:
1. align the options vertically:
`"horizontal": False,`

2. use [multi-rate schema](https://potato-annotation.readthedocs.io/en/latest/schemas_and_templates/#multirate) where the labels will be displayed at the top of the radio button:

```
"annotation_schemes": [      
        {
            "annotation_type": "multirate",

            # This name gets used in reporting the annotation results
            "name": "awesomeness",

            # This text is shown to the user and can be a longer statement
            "description": "How awesome is this?",

            "display_config": {
                                "num_columns":1
            },

            "arrangement":'vertical',

            "options": ['Option 1', 'Option 2', 'Option 3'],
            "labels": ['Strongly disagree', 'Disagree', 'Neutral', 'Agree' , 'Strongly Agree'],

            # adding requirements for labels, when "required" is True, the annotators will be asked to finish the current instance to proceed
            "label_requirement": { "required": True },

            # If true, keys [1-size] will be bound to scale responses. Likert
            # scales larger than 10 are not supported with this simple
            # keybinding and will need to use the full item specification to
            # bind all scale points to keys.
            "sequential_key_binding": True,

            # Whether randomizing the order of the options
            "option_randomization": True
        }       
  ]
```

**Comment by jl3676** [comment]
@Jiaxin-Pei Hi, thanks for your reply. I tried the multirate schema but it didn't space out my options because they are short. For my purpose, I'd prefer to keep my options horizontal, so just double-checking that there's no other way to do this?

**Comment by Jiaxin-Pei** [comment]
@jl3676 one simple solution is to add `&nbsp;` to each label:
```
"labels": [
               "pizza&nbsp;&nbsp;", "bagels&nbsp;&nbsp;", "burgers&nbsp;&nbsp;", "curry&nbsp;&nbsp;", "tacos&nbsp;&nbsp;",
            ],
```

**Comment by jl3676** [comment]
that worked! thanks. closing the issue
