### ISSUE TITLE
Different colors for multiple span annotation schemas

### ISSUE THREAD

**Issue by Dennis1989** [davidjurgens/potato#95]
Let's assume we have a task involving multiple span annotation schemas. There's a valid reason for keeping them separate instead of merging them into a single schema. It would be helpful if each schema started with a different color to avoid confusion for the annotators. At the moment, both schemas use the same color, which could lead to confusion. A screenshot is attached for reference.

![Bildschirmfoto 2024-10-01 um 15 24 24](https://github.com/user-attachments/assets/d7361d00-f509-43e5-8bee-d40e5671b301)

**Comment by TFlexSoom** [comment]
@Dennis1989 Closed this for now, feel free to re-open if you're still having issues or if I didn't solve the entire issue.

Cheers!
